=== BISONNL/predefined/xsd/predefined-bison-v910.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright:                                                                        -->
<!--     Dit document is eigendom van Platform BISON onder de Stichting Connekt        -->
<!--     en wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl,        -->
<!--     zie http://creativecommons.org/licences/by-nd/3.0/nl                          -->
<!-- Dit XSD is onderdeel van het TMI9 NeTEx Nederlands profiel                        -->
<!-- Versie:  v9.1.0                                                                   -->
<!-- Historie:                                                                         -->
<!--   v9.1.0 (mei 2019)                                                               -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<xsd:schema xmlns="http://www.netex.org.uk/netex" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.netex.org.uk/netex" elementFormDefault="qualified" version="9.1.0" id="predefined-bison-xsd">
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- GEGEVENS STRUCTUREN                                                                                     -->
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <xsd:simpleType name="predefinedValuesBISON">
    <xsd:annotation>
      <xsd:documentation>Voorgedefinieerde identificatie voor frames met TypeOfService, TypeOfActivation of TypeOfEquipment waarden</xsd:documentation>
    </xsd:annotation>
    <xsd:restriction base="xsd:string">
      <xsd:enumeration value="BISON:TypeOfServiceValues"/>
      <xsd:enumeration value="BISON:TypeOfActivationValues"/>
      <xsd:enumeration value="BISON:TypeOfEquipmentValues"/>
    </xsd:restriction>
  </xsd:simpleType>
  <xsd:complexType name="typeOfValue">
    <xsd:sequence>
      <xsd:element name="Name" type="xsd:string"/>
      <xsd:element name="Description" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" form="unqualified"/>
  </xsd:complexType>
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <!-- GEGEVENSLEVERING                                                                                        -->
  <!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
  <xsd:element name="PublicationDelivery">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element name="PublicationTimestamp" type="xsd:string"/>
        <xsd:element name="ParticipantRef" type="xsd:string"/>
        <xsd:element name="Description" type="xsd:string" minOccurs="0"/>
        <xsd:element name="dataObjects">
          <xsd:complexType>
            <xsd:sequence>
              <xsd:element name="GeneralFrame" type="generalFrame" maxOccurs="unbounded"/>
            </xsd:sequence>
          </xsd:complexType>
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="version" type="xsd:string" use="required" form="unqualified"/>
    </xsd:complexType>
  </xsd:element>
  <xsd:complexType name="generalFrame">
    <xsd:sequence>
      <xsd:element name="Description" type="xsd:string"/>
      <xsd:element name="TypeOfFrameRef">
        <xsd:complexType>
          <xsd:attribute name="ref" type="predefinedValuesBISON" use="required" form="unqualified"/>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="members">
        <xsd:complexType>
          <xsd:sequence>
            <xsd:element name="ValueSet" type="valueSet"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" form="unqualified"/>
    <xsd:attribute name="version" type="xsd:string" use="required" form="unqualified"/>
  </xsd:complexType>
  <xsd:complexType name="valueSet">
    <xsd:sequence>
      <xsd:element name="values">
        <xsd:complexType>
          <xsd:choice>
            <xsd:element name="TypeOfService" type="typeOfValue" maxOccurs="unbounded"/>
            <xsd:element name="TypeOfActivation" type="typeOfValue" maxOccurs="unbounded"/>
            <xsd:element name="TypeOfEquipment" type="typeOfValue" maxOccurs="unbounded"/>
          </xsd:choice>
          <!-- LET OP: De geleverde lijst moet overeenstemmen met het TypeOfFrame! -->
        </xsd:complexType>
      </xsd:element>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:string" use="required" form="unqualified"/>
  </xsd:complexType>
</xsd:schema>

=== BISONNL/predefined/xml/bison-TypeOfActivationValues.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright:                                                                        -->
<!--     Dit document is eigendom van Platform BISON onder Samenwerkingsverband DOVA   -->
<!--     en wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl,        -->
<!--     zie http://creativecommons.org/licences/by-nd/3.0/nl                          -->
<!-- Dit XSD is gerelateerd aan het TMI9 NeTEx NL Profiel en het TMI9 SIRI NL Profiel  -->
<!--                                                                                   -->
<!-- Versie:  v20190501a                                                               -->
<!--                                                                                   -->
<!-- Historie:                                                                         -->
<!--   v20190501  (mei 2019)     initiele versie                                       -->
<!--   v20190501a (januari 2020) copyright aangepast                                   -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<PublicationDelivery xmlns="http://www.netex.org.uk/netex" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.netex.org.uk/netex predefined-bison-v910.xsd" version="9.1.0">
	<PublicationTimestamp>2019-05-01T00:00:00Z</PublicationTimestamp>
	<ParticipantRef>BISON</ParticipantRef>
	<Description>BISON lijst met voorgedefinieerde KAR meldpunt typen, versie 20190501</Description>
	<dataObjects>
		<GeneralFrame id="BISON:GeneralFrame:Predefined_TypeOfActivation" version="20190501">
			<Description>Lijst met voorgedefinieerde KAR meldpunt typen. Deze lijst wordt bijgehouden door BISON. De lijstelementen (TypeOfActivation) kunnen desgewenst (ongewijzigd!) worden overgenomen in een gegevenslevering conform het Nederlands NeTEx Profiel.</Description>
			<TypeOfFrameRef ref="BISON:TypeOfActivationValues"/>
			<members>
				<ValueSet id="BISON:ValueSet:TypeOfActivation">
					<values>
						<TypeOfActivation id="BISON:TypeOfActivation:PreAnnouncement">
							<Name>PreAnnouncement</Name>
							<Description>Vooraanmelding</Description>
						</TypeOfActivation>
						<TypeOfActivation id="BISON:TypeOfActivation:Announcement">
							<Name>Announcement</Name>
							<Description>Aanmelding</Description>
						</TypeOfActivation>
						<TypeOfActivation id="BISON:TypeOfActivation:HaltLine">
							<Name>HaltLine</Name>
							<Description>Stopstreep</Description>
						</TypeOfActivation>
						<TypeOfActivation id="BISON:TypeOfActivation:LeaveMessage">
							<Name>LeaveMessage</Name>
							<Description>Uitmelding</Description>
						</TypeOfActivation>
					</values>
				</ValueSet>
			</members>
		</GeneralFrame>
	</dataObjects>
</PublicationDelivery>

=== BISONNL/predefined/xml/bison-TypeOfEquipmentValues.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright:                                                                        -->
<!--     Dit document is eigendom van Platform BISON onder Samenwerkingsverband DOVA   -->
<!--     en wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl,        -->
<!--     zie http://creativecommons.org/licences/by-nd/3.0/nl                          -->
<!-- Dit XSD is gerelateerd aan het TMI9 NeTEx NL Profiel en het TMI9 SIRI NL Profiel  -->
<!--                                                                                   -->
<!-- Versie:  v20190501a                                                               -->
<!--                                                                                   -->
<!-- Historie:                                                                         -->
<!--   v20190501  (mei 2019)     initiele versie                                       -->
<!--   v20190501a (januari 2020) copyright aangepast                                   -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<PublicationDelivery xmlns="http://www.netex.org.uk/netex" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.netex.org.uk/netex predefined-bison-v910.xsd" version="9.1.0">
	<PublicationTimestamp>2019-05-01T00:00:00Z</PublicationTimestamp>
	<ParticipantRef>BISON</ParticipantRef>
	<Description>BISON lijst met voorgedefinieerde soorten apparatuur m.b.t. toegankelijkheid, versie 20190501</Description>
	<dataObjects>
		<GeneralFrame id="BISON:GeneralFrame:Predefined_TypeOfEquipment" version="20190501">
			<Description>Lijst met voorgedefinieerde soorten apparatuur m.b.t. toegankelijkheid. Deze lijst wordt bijgehouden door BISON. De lijstelementen (TypeOfEquipment) kunnen desgewenst (ongewijzigd!) worden overgenomen in een gegevenslevering conform het Nederlands NeTEx Profiel.</Description>
			<TypeOfFrameRef ref="BISON:TypeOfEquipmentValues"/>
			<members>
				<ValueSet id="BISON:ValueSet:TypeOfEquipment">
					<values>
						<TypeOfEquipment id="BISON:TypeOfEquipment:automaticRamp">
							<Name>automaticRamp</Name>
							<Description>Elektrische oprijplaat</Description>
						</TypeOfEquipment>
						<TypeOfEquipment id="BISON:TypeOfEquipment:manualRamp">
							<Name>manualRamp</Name>
							<Description>Handbediende oprijplaat</Description>
						</TypeOfEquipment>
						<TypeOfEquipment id="BISON:TypeOfEquipment:slidingStep">
							<Name>slidingStep</Name>
							<Description>Opstaptrede</Description>
						</TypeOfEquipment>
						<TypeOfEquipment id="BISON:TypeOfEquipment:wheelchairLift">
							<Name>wheelchairLift</Name>
							<Description>Rolstoellift</Description>
						</TypeOfEquipment>
						<!-- WELLICHT NOG AANVULLEN -->
					</values>
				</ValueSet>
			</members>
		</GeneralFrame>
	</dataObjects>
</PublicationDelivery>

=== BISONNL/predefined/xml/bison-TypeOfServiceValues.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<!-- Copyright: -->
<!--     Dit document is eigendom van Platform BISON onder de Stichting Connekt -->
<!--     en wordt gepubliceerd onder de Creative Commons Licentie by-nd/3.0/nl, -->
<!--     zie http://creativecommons.org/licences/by-nd/3.0/nl -->
<!-- Dit bestand is gerelateerd aan v9.1.0 van het TMI9 NeTEx Nederlands profiel -->
<!-- Versie:  20190501 -->
<!-- Historie: -->
<!--   v20190501 (mei 2019): initiele versie -->
<!-- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -->
<PublicationDelivery xmlns="http://www.netex.org.uk/netex" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.netex.org.uk/netex predefined-bison-v910.xsd" version="9.1.0">
	<PublicationTimestamp>2019-05-01T00:00:00Z</PublicationTimestamp>
	<ParticipantRef>BISON</ParticipantRef>
	<Description>BISON lijst met voorgedefinieerde formules (lijnkenmerken), versie 20190501</Description>
	<dataObjects>
		<GeneralFrame id="BISON:GeneralFrame:Predefined_TypeOfService" version="20190501">
			<Description>Lijst met voorgedefinieerde formules (lijnkenmerken). Deze lijst wordt bijgehouden door BISON. De lijstelementen (TypeOfService) kunnen desgewenst (ongewijzigd!) worden overgenomen in een gegevenslevering conform het Nederlands NeTEx Profiel.</Description>
			<TypeOfFrameRef ref="BISON:TypeOfServiceValues"/>
			<members>
				<ValueSet id="BISON:ValueSet:TypeOfService">
					<values>
						<TypeOfService id="BISON:TypeOfService:Flex">
							<Name>Flex</Name>
							<Description>Flexibel vervoer</Description>
						</TypeOfService>
						<!-- NOG VERDER AAN TE VULLEN -->
					</values>
				</ValueSet>
			</members>
		</GeneralFrame>
	</dataObjects>
</PublicationDelivery>
